services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/static.yml:/traefik.yml:ro
      - ./config/traefik/dynamic.yml:/dynamic.yml:ro
    networks:
      - main-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main-network

  fastapi:
    image: fastapi:latest
    container_name: fastapi
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      SHARED_FOLDER: ${SHARED_FOLDER}
    volumes:
      - ./data/fastapi/shared:/home/appuser/shared
    depends_on:
      - postgres
      - traefik
    networks:
      - main-network

  # main:
  #   image: main:latest
  #   container_name: main
  #   restart: unless-stopped
  #   environment:
  #     NEXT_PUBLIC_BASE_PATH: ""
  #   depends_on:
  #     - traefik
  #     - fastapi
  #   networks:
  #     - main-network

networks:
  main-network:
    driver: bridge
